name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1   # v7.0.1
      - name: Run shellcheck on all scripts
        run: |
          shopt -s globstar
          shellcheck $(git ls-files '**/*.sh')

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1   # v7.0.1
      - name: Install yamllint
        run: pipx install yamllint
      - name: Lint compose files
        run: |
          yamllint -d relaxed docker-compose.*.yml
          yamllint -d relaxed cron.d/* systemd/*.conf

  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1   # v7.0.1
        with:
          fetch-depth: 0
      - name: Run gitleaks
        run: |
          ghcr.io/gitleaks/gitleaks:v8.30.1 detect --log-opts "HEAD~..HEAD"

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1   # v7.0.1
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@fac544c07dec837dccb6301d7b5580bf5edae39 # v8.2.0
      - name: Run pre-commit hooks
        run: uvx --from pre-commit pre-commit run --all-files
